// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package resource_share

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/ram"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/ram/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ram-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ResourceShare{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()

	// Check if we're in Accept Mode (acceptInvitation is set)
	if r.ko.Spec.AcceptInvitation != nil {
		return rm.sdkFindAcceptedInvitation(ctx, r)
	}

	// Original Create Mode logic
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	if r.ko.Status.OwningAccountID != nil && *r.ko.Status.OwningAccountID == string(rm.awsAccountID) {
		input.ResourceOwner = svcsdktypes.ResourceOwnerSelf
	} else {
		input.ResourceOwner = svcsdktypes.ResourceOwnerOtherAccounts
	}
	var resp *svcsdk.GetResourceSharesOutput
	resp, err = rm.sdkapi.GetResourceShares(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "GetResourceShares", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UnknownResourceException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ResourceShares {
		if elem.AllowExternalPrincipals != nil {
			ko.Spec.AllowExternalPrincipals = elem.AllowExternalPrincipals
		} else {
			ko.Spec.AllowExternalPrincipals = nil
		}
		if elem.CreationTime != nil {
			ko.Status.CreationTime = &metav1.Time{*elem.CreationTime}
		} else {
			ko.Status.CreationTime = nil
		}
		if elem.FeatureSet != "" {
			ko.Status.FeatureSet = aws.String(string(elem.FeatureSet))
		} else {
			ko.Status.FeatureSet = nil
		}
		if elem.LastUpdatedTime != nil {
			ko.Status.LastUpdatedTime = &metav1.Time{*elem.LastUpdatedTime}
		} else {
			ko.Status.LastUpdatedTime = nil
		}
		if elem.Name != nil {
			ko.Spec.Name = elem.Name
		} else {
			ko.Spec.Name = nil
		}
		if elem.OwningAccountId != nil {
			ko.Status.OwningAccountID = elem.OwningAccountId
		} else {
			ko.Status.OwningAccountID = nil
		}
		if elem.ResourceShareArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ResourceShareArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.Status != "" {
			ko.Status.Status = aws.String(string(elem.Status))
		} else {
			ko.Status.Status = nil
		}
		if elem.StatusMessage != nil {
			ko.Status.StatusMessage = elem.StatusMessage
		} else {
			ko.Status.StatusMessage = nil
		}
		if elem.Tags != nil {
			f9 := []*svcapitypes.Tag{}
			for _, f9iter := range elem.Tags {
				f9elem := &svcapitypes.Tag{}
				if f9iter.Key != nil {
					f9elem.Key = f9iter.Key
				}
				if f9iter.Value != nil {
					f9elem.Value = f9iter.Value
				}
				f9 = append(f9, f9elem)
			}
			ko.Spec.Tags = f9
		} else {
			ko.Spec.Tags = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	if err = rm.getPermissionArns(ctx, &resource{ko}); err != nil {
		return nil, err
	}

	if err = rm.getResourceShareAssociations(ctx, &resource{ko}); err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	// In Accept Mode, Name is not required (we use ShareARN instead)
	if r.ko.Spec.AcceptInvitation != nil {
		return false
	}
	// In Create Mode, Name is required
	return r.ko.Spec.Name == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.GetResourceSharesInput, error) {
	res := &svcsdk.GetResourceSharesInput{}

	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()

	// Check if we're in Accept Mode (acceptInvitation is set)
	if desired.ko.Spec.AcceptInvitation != nil {
		return rm.sdkAcceptInvitation(ctx, desired)
	}

	// Create Mode: Validate that name is provided
	if desired.ko.Spec.Name == nil || *desired.ko.Spec.Name == "" {
		return nil, ackerr.NewTerminalError(fmt.Errorf(
			"spec.name is required when not in Accept Mode (acceptInvitation is not set)"))
	}

	// Original Create Mode logic
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateResourceShareOutput
	_ = resp
	resp, err = rm.sdkapi.CreateResourceShare(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateResourceShare", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ResourceShare.AllowExternalPrincipals != nil {
		ko.Spec.AllowExternalPrincipals = resp.ResourceShare.AllowExternalPrincipals
	} else {
		ko.Spec.AllowExternalPrincipals = nil
	}
	if resp.ResourceShare.CreationTime != nil {
		ko.Status.CreationTime = &metav1.Time{*resp.ResourceShare.CreationTime}
	} else {
		ko.Status.CreationTime = nil
	}
	if resp.ResourceShare.FeatureSet != "" {
		ko.Status.FeatureSet = aws.String(string(resp.ResourceShare.FeatureSet))
	} else {
		ko.Status.FeatureSet = nil
	}
	if resp.ResourceShare.LastUpdatedTime != nil {
		ko.Status.LastUpdatedTime = &metav1.Time{*resp.ResourceShare.LastUpdatedTime}
	} else {
		ko.Status.LastUpdatedTime = nil
	}
	if resp.ResourceShare.Name != nil {
		ko.Spec.Name = resp.ResourceShare.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.ResourceShare.OwningAccountId != nil {
		ko.Status.OwningAccountID = resp.ResourceShare.OwningAccountId
	} else {
		ko.Status.OwningAccountID = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ResourceShare.ResourceShareArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ResourceShare.ResourceShareArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ResourceShare.Status != "" {
		ko.Status.Status = aws.String(string(resp.ResourceShare.Status))
	} else {
		ko.Status.Status = nil
	}
	if resp.ResourceShare.StatusMessage != nil {
		ko.Status.StatusMessage = resp.ResourceShare.StatusMessage
	} else {
		ko.Status.StatusMessage = nil
	}
	if resp.ResourceShare.Tags != nil {
		f9 := []*svcapitypes.Tag{}
		for _, f9iter := range resp.ResourceShare.Tags {
			f9elem := &svcapitypes.Tag{}
			if f9iter.Key != nil {
				f9elem.Key = f9iter.Key
			}
			if f9iter.Value != nil {
				f9elem.Value = f9iter.Value
			}
			f9 = append(f9, f9elem)
		}
		ko.Spec.Tags = f9
	} else {
		ko.Spec.Tags = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateResourceShareInput, error) {
	res := &svcsdk.CreateResourceShareInput{}

	if r.ko.Spec.AllowExternalPrincipals != nil {
		res.AllowExternalPrincipals = r.ko.Spec.AllowExternalPrincipals
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.PermissionARNs != nil {
		res.PermissionArns = aws.ToStringSlice(r.ko.Spec.PermissionARNs)
	}
	if r.ko.Spec.Principals != nil {
		res.Principals = aws.ToStringSlice(r.ko.Spec.Principals)
	}
	if r.ko.Spec.ResourceARNs != nil {
		res.ResourceArns = aws.ToStringSlice(r.ko.Spec.ResourceARNs)
	}
	if r.ko.Spec.Sources != nil {
		res.Sources = aws.ToStringSlice(r.ko.Spec.Sources)
	}
	if r.ko.Spec.Tags != nil {
		f6 := []svcsdktypes.Tag{}
		for _, f6iter := range r.ko.Spec.Tags {
			f6elem := &svcsdktypes.Tag{}
			if f6iter.Key != nil {
				f6elem.Key = f6iter.Key
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, *f6elem)
		}
		res.Tags = f6
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err := rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	if delta.DifferentAt("Spec.PermissionARNs") {
		if err := rm.syncPermissions(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	if delta.DifferentAt("Spec.ResourceARNs") || delta.DifferentAt("Spec.Principals") || delta.DifferentAt("Spec.Sources") {
		if err := rm.syncResourceShareResources(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	if !delta.DifferentExcept("Spec.Tags", "Spec.PermissionARNs", "Spec.ResourceARNs", "Spec.Principals", "Spec.Sources") {
		return desired, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateResourceShareOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateResourceShare(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateResourceShare", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateResourceShareInput, error) {
	res := &svcsdk.UpdateResourceShareInput{}

	if r.ko.Spec.AllowExternalPrincipals != nil {
		res.AllowExternalPrincipals = r.ko.Spec.AllowExternalPrincipals
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ResourceShareArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()

	// Check if we're in Accept Mode
	if r.ko.Spec.AcceptInvitation != nil {
		// In Accept Mode, we need to reject the invitation or leave the share
		// We don't own the share, so we can't delete it
		return rm.sdkRejectOrLeaveShare(ctx, r)
	}

	// Create Mode: Delete the resource share we own
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteResourceShareOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteResourceShare(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteResourceShare", err)
	return nil, err
}

// sdkRejectOrLeaveShare handles deletion for Accept Mode resources
// In Accept Mode, we don't own the share, so we need to handle cleanup:
// 1. If invitation is PENDING: Reject it using RejectResourceShareInvitation
// 2. If invitation is ACCEPTED: Leave the share using DisassociateResourceShare
//
// IMPORTANT: AWS Resource Type Limitations
// -----------------------------------------
// Some AWS resource types do not support self-disassociation from resource shares.
// When a share contains these resource types, attempting to leave the share will
// result in an OperationNotPermittedException error.
//
// Known resource types with this limitation:
//   - Network Firewall (network-firewall:StatefulRulegroup, network-firewall:StatelessRulegroup, etc.)
//
// For these resource types:
//   - Only the share OWNER can remove principals from the share
//   - The receiver CANNOT leave the share themselves
//   - AWS error message: "You cannot leave resource share [...]. The share contains
//     resources of the following resource types, which don't support this action: [...]"
//
// Handling Strategy:
//   - When OperationNotPermittedException is encountered during deletion, we treat it
//     as a successful deletion to allow the Kubernetes resource to be cleaned up
//   - The AWS invitation will remain in ACCEPTED state until the share owner removes
//     the principal or deletes the share
//   - This prevents the Kubernetes resource from getting stuck with a finalizer
//   - A warning is logged to inform operators about the limitation
//
// This is expected AWS behavior and not a bug in the controller.
func (rm *resourceManager) sdkRejectOrLeaveShare(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	rlog.Info("Cleaning up resource share in Accept Mode")

	// Get the invitation ARN, status, and share ARN from the resource
	invitationARN := r.ko.Status.InvitationARN
	invitationStatus := r.ko.Status.InvitationStatus
	shareARN := r.ko.Spec.AcceptInvitation.ShareARN

	if shareARN == nil {
		rlog.Info("No ShareARN in spec, nothing to clean up")
		return nil, nil
	}

	if invitationARN == nil || *invitationARN == "" {
		// No invitation ARN in status, try to find it
		listInput := &svcsdk.GetResourceShareInvitationsInput{
			ResourceShareArns: []string{*shareARN},
		}

		listResp, err := rm.sdkapi.GetResourceShareInvitations(ctx, listInput)
		rm.metrics.RecordAPICall("READ_MANY", "GetResourceShareInvitations", err)
		if err != nil {
			rlog.Info("Failed to find invitation, may already be cleaned up", "error", err)
			return nil, nil
		}

		// Find the invitation (pending or accepted)
		for _, inv := range listResp.ResourceShareInvitations {
			if inv.Status == svcsdktypes.ResourceShareInvitationStatusPending ||
				inv.Status == svcsdktypes.ResourceShareInvitationStatusAccepted {
				invitationARN = inv.ResourceShareInvitationArn
				invitationStatus = aws.String(string(inv.Status))
				break
			}
		}

		if invitationARN == nil {
			rlog.Info("No invitation found, nothing to clean up")
			return nil, nil
		}
	}

	// Check the invitation status
	if invitationStatus != nil && *invitationStatus == "ACCEPTED" {
		// For accepted invitations, we need to disassociate ourselves as a principal
		// This is what the AWS GUI "Leave" button does
		rlog.Info("Leaving accepted resource share by disassociating principal",
			"shareARN", *shareARN)

		// Get our account ID
		accountID := r.ko.Status.ReceiverAccountID
		if accountID == nil || *accountID == "" {
			rlog.Info("No receiver account ID in status, cannot disassociate")
			return nil, ackerr.NewTerminalError(fmt.Errorf("receiver account ID not found in status"))
		}

		// Disassociate ourselves as a principal from the share
		disassociateInput := &svcsdk.DisassociateResourceShareInput{
			ResourceShareArn: shareARN,
			Principals:       []string{*accountID},
		}

		_, err = rm.sdkapi.DisassociateResourceShare(ctx, disassociateInput)
		rm.metrics.RecordAPICall("DELETE", "DisassociateResourceShare", err)
		if err != nil {
			// Check if this is an OperationNotPermittedException
			// Some resource types (e.g., Network Firewall) don't support self-disassociation
			// In this case, only the share owner can remove the principal
			if strings.Contains(err.Error(), "OperationNotPermittedException") {
				rlog.Info("Cannot leave resource share - resource type does not support self-disassociation. " +
					"Only the share owner can remove you from this share. " +
					"Treating as successful deletion to avoid resource getting stuck.",
					"error", err)
				// Return success to allow the Kubernetes resource to be deleted
				// The AWS invitation will remain ACCEPTED until the owner removes the principal
				return nil, nil
			}

			rlog.Info("Failed to disassociate from resource share", "error", err)
			return nil, err
		}

		rlog.Info("Successfully left resource share")
		return nil, nil
	}

	// Invitation is PENDING - we can reject it
	rlog.Info("Rejecting pending resource share invitation", "invitationARN", *invitationARN)
	rejectInput := &svcsdk.RejectResourceShareInvitationInput{
		ResourceShareInvitationArn: invitationARN,
	}

	_, err = rm.sdkapi.RejectResourceShareInvitation(ctx, rejectInput)
	rm.metrics.RecordAPICall("DELETE", "RejectResourceShareInvitation", err)
	if err != nil {
		rlog.Info("Failed to reject resource share invitation", "error", err)
		return nil, err
	}

	rlog.Info("Successfully rejected resource share invitation")
	return nil, nil
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteResourceShareInput, error) {
	res := &svcsdk.DeleteResourceShareInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ResourceShareArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ResourceShare,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "MalformedArnException":
		return true
	default:
		return false
	}
}

// sdkFindAcceptedInvitation finds an accepted invitation for the specified ShareARN
// This is used when spec.acceptInvitation is set (Accept Mode)
func (rm *resourceManager) sdkFindAcceptedInvitation(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFindAcceptedInvitation")
	defer func() {
		exit(err)
	}()

	if r.ko.Spec.AcceptInvitation == nil || r.ko.Spec.AcceptInvitation.ShareARN == nil {
		return nil, ackerr.NotFound
	}

	// Get the invitation for this share ARN
	input := &svcsdk.GetResourceShareInvitationsInput{
		ResourceShareArns: []string{*r.ko.Spec.AcceptInvitation.ShareARN},
	}

	var resp *svcsdk.GetResourceShareInvitationsOutput
	resp, err = rm.sdkapi.GetResourceShareInvitations(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetResourceShareInvitations", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) {
			if awsErr.ErrorCode() == "ResourceShareInvitationArnNotFoundException" ||
				awsErr.ErrorCode() == "UnknownResourceException" {
				return nil, ackerr.NotFound
			}
		}
		return nil, err
	}

	// Find the accepted invitation for this share
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)
	found := false
	var acceptedInvitationARN *string

	for _, invitation := range resp.ResourceShareInvitations {
		// We're looking for an ACCEPTED invitation for this share
		if invitation.Status == svcsdktypes.ResourceShareInvitationStatusAccepted {
			found = true
			acceptedInvitationARN = invitation.ResourceShareInvitationArn
			rm.setResourceFromInvitation(ko, &invitation)
			break
		}
	}

	if !found {
		return nil, ackerr.NotFound
	}

	// Populate resources associated with the invitation
	// This uses the ListPendingInvitationResources API (non-deprecated)
	if acceptedInvitationARN != nil {
		_ = rm.populateInvitationResources(ctx, ko, acceptedInvitationARN)
	}

	return &resource{ko}, nil
}

// sdkAcceptInvitation accepts a pending resource share invitation
// This is used when spec.acceptInvitation is set (Accept Mode)
//
// Accept Mode Overview:
// ---------------------
// In Accept Mode, the ResourceShare CRD is used to accept an incoming resource share
// invitation from another AWS account (cross-account sharing). The workflow is:
//
// 1. Account A (sender) creates a resource share and shares it with Account B (receiver)
// 2. AWS RAM sends an invitation to Account B
// 3. Account B creates a ResourceShare with spec.acceptInvitation.shareARN set
// 4. The controller accepts the invitation and populates status fields
//
// Deletion Behavior:
// ------------------
// When deleting a ResourceShare in Accept Mode:
//   - PENDING invitations: Rejected using RejectResourceShareInvitation
//   - ACCEPTED invitations: Left using DisassociateResourceShare (if supported)
//
// IMPORTANT: Some resource types (e.g., Network Firewall) do not support self-disassociation.
// For these resources, the Kubernetes resource will be deleted successfully, but the AWS
// invitation will remain ACCEPTED until the share owner removes the principal.
// See sdkRejectOrLeaveShare() for detailed documentation on this limitation.
func (rm *resourceManager) sdkAcceptInvitation(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkAcceptInvitation")
	defer func() {
		exit(err)
	}()

	if desired.ko.Spec.AcceptInvitation == nil || desired.ko.Spec.AcceptInvitation.ShareARN == nil {
		return nil, fmt.Errorf("ShareARN is required in acceptInvitation")
	}

	// First, find the pending invitation for this share ARN
	getInput := &svcsdk.GetResourceShareInvitationsInput{
		ResourceShareArns: []string{*desired.ko.Spec.AcceptInvitation.ShareARN},
	}

	var getResp *svcsdk.GetResourceShareInvitationsOutput
	getResp, err = rm.sdkapi.GetResourceShareInvitations(ctx, getInput)
	rm.metrics.RecordAPICall("READ_ONE", "GetResourceShareInvitations", err)
	if err != nil {
		return nil, err
	}

	// Find a pending invitation
	var pendingInvitationARN *string
	for _, invitation := range getResp.ResourceShareInvitations {
		if invitation.Status == svcsdktypes.ResourceShareInvitationStatusPending {
			pendingInvitationARN = invitation.ResourceShareInvitationArn
			break
		}
	}

	if pendingInvitationARN == nil {
		return nil, ackerr.NewTerminalError(fmt.Errorf("no pending invitation found for share ARN %s. "+
			"NOTE: If both AWS accounts are in the same AWS Organization and RAM Sharing with AWS Organizations is enabled, "+
			"this resource is not necessary", *desired.ko.Spec.AcceptInvitation.ShareARN))
	}

	// Accept the invitation
	acceptInput := &svcsdk.AcceptResourceShareInvitationInput{
		ResourceShareInvitationArn: pendingInvitationARN,
	}

	var acceptResp *svcsdk.AcceptResourceShareInvitationOutput
	acceptResp, err = rm.sdkapi.AcceptResourceShareInvitation(ctx, acceptInput)
	rm.metrics.RecordAPICall("CREATE", "AcceptResourceShareInvitation", err)
	if err != nil {
		return nil, err
	}

	ko := desired.ko.DeepCopy()
	rm.setStatusDefaults(ko)
	rm.setResourceFromInvitation(ko, acceptResp.ResourceShareInvitation)

	// Populate resources associated with the invitation
	// This uses the ListPendingInvitationResources API (non-deprecated)
	if acceptResp.ResourceShareInvitation != nil && acceptResp.ResourceShareInvitation.ResourceShareInvitationArn != nil {
		_ = rm.populateInvitationResources(ctx, ko, acceptResp.ResourceShareInvitation.ResourceShareInvitationArn)
	}

	return &resource{ko}, nil
}

// setResourceFromInvitation populates the resource status from an invitation
// This is used in Accept Mode to populate invitation-specific status fields
func (rm *resourceManager) setResourceFromInvitation(
	ko *svcapitypes.ResourceShare,
	invitation *svcsdktypes.ResourceShareInvitation,
) {
	if invitation == nil {
		return
	}

	// Set invitation-specific status fields
	if invitation.ResourceShareInvitationArn != nil {
		ko.Status.InvitationARN = invitation.ResourceShareInvitationArn
	}
	if invitation.Status != "" {
		ko.Status.InvitationStatus = aws.String(string(invitation.Status))
	}
	if invitation.SenderAccountId != nil {
		ko.Status.SenderAccountID = invitation.SenderAccountId
	}
	if invitation.ReceiverAccountId != nil {
		ko.Status.ReceiverAccountID = invitation.ReceiverAccountId
	}
	if invitation.ResourceShareName != nil {
		ko.Status.ShareName = invitation.ResourceShareName
	}
	if invitation.InvitationTimestamp != nil {
		ko.Status.InvitationTime = &metav1.Time{*invitation.InvitationTimestamp}
	}
	if invitation.ResourceShareArn != nil {
		arn := ackv1alpha1.AWSResourceName(*invitation.ResourceShareArn)
		if ko.Status.ACKResourceMetadata == nil {
			ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
		}
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	// Set share status
	if invitation.Status != "" {
		ko.Status.ShareStatus = aws.String(string(invitation.Status))
	}
}

// populateInvitationResources fetches and populates the resources associated with an invitation
// Uses the ListPendingInvitationResources API (replaces deprecated ResourceShareAssociations field)
func (rm *resourceManager) populateInvitationResources(
	ctx context.Context,
	ko *svcapitypes.ResourceShare,
	invitationARN *string,
) error {
	rlog := ackrtlog.FromContext(ctx)

	if invitationARN == nil {
		return nil
	}

	rlog.Info("Fetching resources for invitation using ListPendingInvitationResources API",
		"invitationARN", *invitationARN)

	// List resources associated with the pending invitation
	input := &svcsdk.ListPendingInvitationResourcesInput{
		ResourceShareInvitationArn: invitationARN,
	}

	resp, err := rm.sdkapi.ListPendingInvitationResources(ctx, input)
	rm.metrics.RecordAPICall("READ", "ListPendingInvitationResources", err)
	if err != nil {
		// Don't fail the whole operation if we can't list resources
		// Just log and continue
		rlog.Info("Failed to list pending invitation resources (non-fatal)", "error", err)
		return nil
	}

	if resp.Resources != nil && len(resp.Resources) > 0 {
		resources := make([]*string, 0, len(resp.Resources))
		for _, resource := range resp.Resources {
			if resource.Arn != nil {
				resources = append(resources, resource.Arn)
			}
		}
		if len(resources) > 0 {
			ko.Status.Resources = resources
			rlog.Info("Populated resources from invitation", "resourceCount", len(resources))
		}
	} else {
		rlog.Info("No resources found in invitation")
	}

	return nil
}
