---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-ram-reader
  namespace: default
rules:
- apiGroups:
  - ram.services.k8s.aws
  resources:
  - resourceshares
  verbs:
  - get
  - list
  - watch
