// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ResourceShareInvitationSpec defines the desired state of ResourceShareInvitation.
//
// Describes an invitation for an Amazon Web Services account to join a resource
// share.
type ResourceShareInvitationSpec struct {

	// Specifies a unique, case-sensitive identifier that you provide to ensure
	// the idempotency of the request. This lets you safely retry the request without
	// accidentally performing the same operation a second time. Passing the same
	// value to a later call to an operation requires that you also pass the same
	// value for all other parameters. We recommend that you use a UUID type of
	// value. (https://wikipedia.org/wiki/Universally_unique_identifier).
	//
	// If you don't provide this value, then Amazon Web Services generates a random
	// one for you.
	//
	// If you retry the operation with the same ClientToken, but with different
	// parameters, the retry fails with an IdempotentParameterMismatch error.
	ClientToken *string `json:"clientToken,omitempty"`
	// The Amazon Resource Name (ARN) (https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
	// of the invitation that you want to accept.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	ResourceShareInvitationARN *string `json:"resourceShareInvitationARN"`
}

// ResourceShareInvitationStatus defines the observed state of ResourceShareInvitation
type ResourceShareInvitationStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date and time when the invitation was sent.
	// +kubebuilder:validation:Optional
	InvitationTimestamp *metav1.Time `json:"invitationTimestamp,omitempty"`
	// The ID of the Amazon Web Services account that received the invitation.
	// +kubebuilder:validation:Optional
	ReceiverAccountID *string `json:"receiverAccountID,omitempty"`
	// The Amazon Resource Name (ARN) (https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
	// of the IAM user or role that received the invitation.
	// +kubebuilder:validation:Optional
	ReceiverARN *string `json:"receiverARN,omitempty"`
	// The Amazon Resource Name (ARN) (https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
	// of the resource share
	// +kubebuilder:validation:Optional
	ResourceShareARN *string `json:"resourceShareARN,omitempty"`
	// To view the resources associated with a pending resource share invitation,
	// use ListPendingInvitationResources.
	// +kubebuilder:validation:Optional
	ResourceShareAssociations []*ResourceShareAssociation `json:"resourceShareAssociations,omitempty"`
	// The name of the resource share.
	// +kubebuilder:validation:Optional
	ResourceShareName *string `json:"resourceShareName,omitempty"`
	// The ID of the Amazon Web Services account that sent the invitation.
	// +kubebuilder:validation:Optional
	SenderAccountID *string `json:"senderAccountID,omitempty"`
	// The current status of the invitation.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
}

// ResourceShareInvitation is the Schema for the ResourceShareInvitations API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="INVITATION-ARN",type=string,priority=0,JSONPath=`.spec.resourceShareInvitationARN`
// +kubebuilder:printcolumn:name="SHARE-ARN",type=string,priority=0,JSONPath=`.status.resourceShareARN`
// +kubebuilder:printcolumn:name="STATUS",type=string,priority=0,JSONPath=`.status.status`
type ResourceShareInvitation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ResourceShareInvitationSpec   `json:"spec,omitempty"`
	Status            ResourceShareInvitationStatus `json:"status,omitempty"`
}

// ResourceShareInvitationList contains a list of ResourceShareInvitation
// +kubebuilder:object:root=true
type ResourceShareInvitationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ResourceShareInvitation `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ResourceShareInvitation{}, &ResourceShareInvitationList{})
}
